# 日本語を使うための設定
spring.datasorce.sqlScriptEncodind: UTF-8

# キャッシュ無効化
spring.thymeleaf.cache: false

spring:
  datasource:
    driverClassName: org.h2.Driver
    # インメモリDBを使う場合
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # ローカルのファイルで永続的に保存する場合(/tmp以下に適当なファイル掘ってる)
    # url: jdbc:h2:file:tmp/testdb
    username: sa
    password: